### ISSUE TITLE
Not working when key attribute contains "-" (minus)

### ISSUE THREAD

**Issue by guitar-hero** [jacwright/array-query#10]
Hello there,

We were about to use your library when suddenly we encountered an issue.
When the key name contains an "-", the queries won't work.

here is an example

```
var query = require('array-query');

var basicMat_ = [{
    "name": "Jack", "s_mat_atv_randvoll": 1030}, {
    "name": "Sparrow", "s_mat_atv_randvoll": 716}, {
    "name": "Alf", "s_mat_atv_randvoll": 1030}]

var basicMatMinus = [{
    "name": "Jack", "s-mat-atv-randvoll": 1030}, {
    "name": "Sparrow", "s-mat-atv-randvoll": 716}, {
    "name": "Alf", "s-mat-atv-randvoll": 1030}]

var q3 = query("s_mat_atv_randvoll").gt(800).on(basicMat_)
var q4 = query("s-mat-atv-randvoll").gt(800).on(basicMatMinus)

console.log('q3', q3)
console.log('q4', q4)
```

q3 returns the first and last entry
q4 returns an empty array

is there any fix for that?

Thanks and best regards, G

**Comment by guitar-hero** [comment]
Hi

I just wanted to inform you that we've decided to rename our keys so the problem doesn't happen.

best regards, G

**Comment by jacwright** [comment]
I've added a fix for this if you decide to go back to using dashes.
