### ISSUE TITLE
fix my contribute reference

### ISSUE THREAD

**Issue by mateusmcordeiro** [jacwright/array-query#16]
First of all, nicely done about the last updates (typescript and some enhancements).

About the issue topic:

I forgot to change my git config from the arrayquery local project after i cloned the project.  Because that, all my commits reference are without any reference to any git account (its using my work email). So i would be very happy if you run this script to fix the repo.
The problem doing this script execution is you are going to need to push force. So i dont know if this would be a big problem. I`ve tested it locally and it worked. 

If im asking too much, let me know and close this issue, it was my mistake, so there is no problem if you refuse.

script:
```
#!/bin/sh

git filter-branch --env-filter '
OLD_EMAIL="mateus.cordeiro@soupilar.com.br"
CORRECT_NAME="Mateus Cordeiro"
CORRECT_EMAIL="mateusmcordeiro@hotmail.com"
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
```

**Comment by jacwright** [comment]
Sure. Done. You'll need to force pull I believe as well.
