### ISSUE TITLE
Add typings definition

### ISSUE THREAD

**Issue by no-more** [jacwright/array-query#7]
Hello,

Your util looks great, I'll try to implement it in my next project. I was wondering if it would be possible to implement typings definition for this ? I'll be working with angular2 and typescript so it would be great to be able to have the definition.

Thanks a lot.

Best regards

**Comment by jacwright** [comment]
"typings definition"? I'm not sure what you mean by that.

**Comment by no-more** [comment]
Hi,

With typescript there's a tool called typings which is just a registery(http://definitelytyped.org/) of javascript library definition. For example Jquery, pouchdb, localforage ... and many other. Those lib are not written in typescript, they just provide an interface definition which then can be used with typescript IDE for advanced autocompletion.

I don't know how to write one yet but they are getting very popular as typescript is getting more and more present.

Thanks for your lib, I haven't yet used it very much (needs to complete lots of other thing before getting into this) but it look very powerfull.

**Comment by mateusmcordeiro** [comment]
I think this is a good enhancement, so i think i will get it to do soon.

**Comment by jacwright** [comment]
Moved over to Typescript with fixes for newer JS versions. #15 closes this.
