### ISSUE TITLE
Method filter is not supported on IE11

### ISSUE THREAD

**Issue by shrzmk** [jacwright/array-query#9]
I am using array-query for an array of objects in client-side JavaScript by placing query.js file. It shows this error "Object doesn't support property or method 'filter'". Even on chrome array.filter is not supported. Please let me know how can resolve this.

**Comment by jacwright** [comment]
Array `filter` is available on IE9+ (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Browser_compatibility). You need to be sure to pass in an array, which is what is going wrong.

I committed an array-check (see the commit ☝️) that will help provide a better error message for triaging this type of issue.

**Comment by shrzmk** [comment]
Thanks @jacwright . I was directly passing json data which consists array of objects.
